### ISSUE TITLE
Failed to execute "select distinct sourcesystem_cd from i2b2metadata.i2b2" in postgres

### ISSUE THREAD

**Issue by ghost** [ThomsonReuters-LSPS/tMDataLoader#71]
Hello,
I just installed transmart1.2.5 and setup DB to work tMDataLoader1.2.4. I tried loading data and got the attached error. 

please what can do to resolve this?
Thanks

**Comment by Ayinks** [comment]
/home/transmart/Desktop/Error.pdf
